name: Docker image CI
on:
  push:
     branches: [ "main" ]
jobs:
   docker-build:
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v3
           - name: Build the Docker image
             run: |
                  docker build . --file Dockerfile --tag hackthenumber
                  docker login -u ${{secrets.USERNAME}} -p ${{secrets.TOKEN}}
                  docker tag hackthenumber ${{secrets.USERNAME}}/hackthenumber
                  docker push ${{secrets.USERNAME}}/hackthenumber
