name: Docker image CI
on:
  push:
     branches: [ "main" ]
jobs:
   docker-build:
        runs-on: ubuntu-latest
        steps:
           - uses: actions/checkout@v3
           - name: Build the Docker image
             run: |
                  docker build . --file Dockerfile --tag hackthenumber
                  docker login -u ${{secret.USERNAME}} -p ${{secret.TOKEN}}
                  docker tag mysite ${{secret.USERNAME}}/hackthenumber
                  docker push ${{secret.USERNAME}}/hackthenumber
